-- GROUPBY로 묶어주고 COUNT해야 제대로 값 나옴!
-- LIKE절 공통점 뽑아내서 %시트%로 찾기
-- 오름차순 정렬이라 ASC 생략
SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE