-- 문제: 동일한 회원이 동일한 제품을 재구매한 데이터를 출력(USER_ID, PRODUCT_ID), 회원 오름차순&동일하면 상품 내림차순

-- 방법 1: GROUP BY로 USER_ID와 PRODUCT_ID를 묶은 후 PRODUCT_ID로 2번 이상 나온걸 세서 찾기
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(PRODUCT_ID)>1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;

-- 방법 2: 셀프 조인 조건으로 ON에 재구매를 넣고, 셀프 조인이라 중복으로 뜨는걸 막기 위해 DISTINCT와 SALES_DATE 조건 추가
SELECT DISTINCT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A JOIN ONLINE_SALE B
ON A.USER_ID=B.USER_ID AND A.PRODUCT_ID=B.PRODUCT_ID
WHERE A.SALES_DATE != B.SALES_DATE
ORDER BY USER_ID ASC, PRODUCT_ID DESC;